import pandas as pd
var1=pd.DataFrame({"ID":[1,2,3,4,5,6,7,8,9,10],"Name":["A","B","C","D","E","F","G","H","I","J"]},index=["a","b","c","d","e","f","g","h","i","j"])
var2=pd.DataFrame({"ID":[1,2,3,4,5,6,7,8,9,10],"Number":["11","22","33","44","55","66","77","88","99","00"]},index=["a","b","c","d","e","f","g","h","i","j"])
print(var1.join(var2,lsuffix="_1",rsuffix="_2"))
print(var1.join(var2,lsuffix="_1",rsuffix="_2"))

var1=pd.DataFrame({"ID":[1,2,3,4,5,6,7,8,9,10],"Name":["A","B","C","D","E","F","G","H","I","J"]},index=["a","b","c","d","e","f","g","h","i","j"])
var2=pd.DataFrame({"ID":[1,2,3,4,5],"Number":["11","22","33","44","55"]},index=["a","b","c","d","e"])
print(var1.join(var2,lsuffix="_1",rsuffix="_2"))
print(var2.join(var1,lsuffix="_1",rsuffix="_2"))
print()
print(var2.join(var1,lsuffix="_1",rsuffix="_2",how="right"))
print(var2.join(var1,lsuffix="_1",rsuffix="_2",how="inner"))
print(var2.join(var1,lsuffix="_1",rsuffix="_2",how="outer"))
print()
print()
print()
print("APPEND")
print(var1._append(var2))
