import pandas as pd
x=pd.read_csv("C:\\Users\\supriya shrivastv\\PycharmProjects\\Pandas\\CSV\\Test1")
print(x)
y=pd.read_csv("C:\\Users\\supriya shrivastv\\PycharmProjects\\Pandas\\CSV\\Test1",nrows=1)
print(y)
y=pd.read_csv("C:\\Users\\supriya shrivastv\\PycharmProjects\\Pandas\\CSV\\Test1",usecols=[0,1])
print(y)
y=pd.read_csv("C:\\Users\\supriya shrivastv\\PycharmProjects\\Pandas\\CSV\\Test1",index_col=("a"))
print(y)
y=pd.read_csv("C:\\Users\\supriya shrivastv\\PycharmProjects\\Pandas\\CSV\\Test1",names=("col1","col2","col3","col4","col5"))
print(y)
y=pd.read_csv("C:\\Users\\supriya shrivastv\\PycharmProjects\\Pandas\\CSV\\Test1",header=None,prefix="col")
print(y)
y=pd.read_csv("C:\\Users\\supriya shrivastv\\PycharmProjects\\Pandas\\CSV\\Test1",dtype={"a":"float"})
print(y)